name: Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Publish to Version Catalog
        uses: ClipMX/mobile.android.blaze.versions-catalog@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          packages_token: ${{ secrets.PACKAGES_TOKEN }}
          packages_user: ${{ secrets.PACKAGES_USERNAME }}
